//../test/ComDriverTasks.v
//../test/ComRxDriverTasks.v
//../test/ComTxDriverTasks.v
../test/DummyCard.v
../test/FiDiAnalyzer.v
../test/HammingWeight.v
//../test/HexStringConversion.v
../test/iso7816_3_t0_analyzer.v
../test/Iso7816_directionProbe.v
//../test/RxCoreTestBench.v
../test/tb_BasicHalfDuplexUart.v
../test/tb_HalfDuplexUartIf.v
../test/tbIso7816_3_Master.v
../test/TriWire.v
../test/tsAnalyzer.v
../test/TxCoreTestBench.v
